# Generated by Django 5.0.2 on 2024-02-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date_ordered",
            new_name="date_orderd",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
