# Generated by Django 5.0.2 on 2024-02-28 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_rename_date_ordered_order_date_orderd_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="data_added",
            new_name="date_added",
        ),
    ]
