# Generated by Django 5.0.2 on 2024-02-28 07:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_rename_data_added_orderitem_date_added"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date_orderd",
            new_name="date_ordered",
        ),
    ]
